// Curated classic-era make → model list for the FantomWorks self-submission form.
// Focused on pre-1973 American + common import classics the shop actually works on.
// Free-text is always allowed; this only powers the datalist type-ahead suggestions.
export const VEHICLES: Record<string, string[]> = {
  AMC: ['AMX', 'Ambassador', 'Javelin', 'Rambler', 'Rebel'],
  Buick: ['Electra', 'Gran Sport', 'LeSabre', 'Riviera', 'Skylark', 'Wildcat'],
  Cadillac: ['Coupe DeVille', 'DeVille', 'Eldorado', 'Fleetwood', 'Series 62'],
  Chevrolet: [
    'Bel Air',
    'Camaro',
    'Caprice',
    'Chevelle',
    'Corvair',
    'Corvette',
    'El Camino',
    'Impala',
    'Nova',
    'C10',
    'K10',
  ],
  Chrysler: ['300', 'Imperial', 'New Yorker', 'Newport', 'Town & Country'],
  Datsun: ['240Z', '510', '1600', '2000 Roadster'],
  Dodge: ['Challenger', 'Charger', 'Coronet', 'Dart', 'Super Bee'],
  Ford: [
    'Bronco',
    'Fairlane',
    'Falcon',
    'Galaxie',
    'Mustang',
    'Ranchero',
    'Thunderbird',
    'Torino',
    'F-100',
    'F-250',
  ],
  GMC: ['Jimmy', 'Sierra', 'Suburban', 'C1500'],
  Jaguar: ['E-Type', 'Mark 2', 'XK120', 'XK140', 'XK150', 'XKE'],
  Jeep: ['CJ-5', 'CJ-7', 'Gladiator', 'Wagoneer'],
  Lincoln: ['Continental', 'Mark III', 'Mark IV', 'Premiere'],
  Mercury: ['Comet', 'Cougar', 'Cyclone', 'Montego', 'Monterey'],
  MG: ['MGA', 'MGB', 'MGB GT', 'Midget'],
  Oldsmobile: ['442', 'Cutlass', 'Delta 88', 'Toronado'],
  Plymouth: [
    'Barracuda',
    'Belvedere',
    "'Cuda",
    'Fury',
    'GTX',
    'Road Runner',
    'Satellite',
    'Valiant',
  ],
  Pontiac: ['Bonneville', 'Catalina', 'Firebird', 'GTO', 'LeMans', 'Tempest', 'Trans Am'],
  Porsche: ['356', '911', '912', '914'],
  Studebaker: ['Avanti', 'Champion', 'Hawk', 'Lark'],
  Triumph: ['GT6', 'Spitfire', 'TR3', 'TR4', 'TR6'],
  Volkswagen: ['Beetle', 'Karmann Ghia', 'Type 2 / Bus', 'Type 3'],
  Volvo: ['122 Amazon', '1800', 'P1800'],
}

export const MAKES = Object.keys(VEHICLES)
